version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: redis:7-alpine
    ports: ["6379:6379"]
  server:
    build: ./server
    env_file: .env
    environment:
      NODE_ENV: development
    ports: ["3001:3001"]
    depends_on:
      - db
      - cache
  web:
    build: ./web
    env_file: .env
    environment:
      NEXT_PUBLIC_SHOPIFY_API_KEY: ${SHOPIFY_API_KEY}
      NEXT_PUBLIC_APP_URL: ${APP_URL}
    ports: ["3000:3000"]
    depends_on:
      - server
volumes:
  pgdata:
